sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Yy19960108!
  alioss:
    endpoint: 127.0.0.1:9000
    access-key-id: minioadmin
    access-key-secret: minioadmin
    bucket-name: sky-take-out
